# Generated by Django 4.2.21 on 2025-05-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('University', 'University'), ('Football', 'Football'), ('Plaza', 'Plaza')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
