# Generated by Django 4.2.21 on 2025-05-16 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-id',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
