# Generated by Django 4.2.21 on 2025-05-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('banner', 'Banner'), ('default', 'Default')], default='default', max_length=155, verbose_name='Тип картинки'),
        ),
    ]
