# Generated by Django 4.2.21 on 2025-05-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footballer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birthday', models.DateField(verbose_name='День рождения')),
                ('number', models.IntegerField(default=0, verbose_name='Игровой номер')),
                ('height', models.IntegerField(default=0, verbose_name='Рост')),
                ('weight', models.IntegerField(default=0, verbose_name='Вес')),
                ('citizenship', models.CharField(max_length=255, verbose_name='Гражданство')),
                ('position', models.CharField(choices=[('Вратарь', 'Goalkeeper'), ('Защитник', 'Defender'), ('Полузащитник', 'Midfielder'), ('Нападающий', 'Forward')], max_length=155, verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ('-id',),
            },
        ),
    ]
