# Generated by Django 4.2.21 on 2025-05-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballer',
            name='image',
            field=models.FileField(default=1, upload_to='footballer', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footballer',
            name='citizenship',
            field=models.CharField(choices=[('Кыргызское', 'Kyrgyz'), ('Российское', 'Russian'), ('Казахское', 'Kazakh'), ('Бразильское', 'Brazilian')], max_length=255, verbose_name='Гражданство'),
        ),
    ]
