# Generated by Django 4.2.21 on 2025-05-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballers', '0002_footballer_image_alter_footballer_citizenship'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballer',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Слаг'),
        ),
    ]
