# Generated by Django 4.2.21 on 2025-05-20 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('footballers', '0004_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('thumbnail', models.URLField(blank=True, max_length=500, null=True)),
                ('video', models.URLField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сторис',
                'verbose_name_plural': 'Сторисы',
                'ordering': ['-date'],
            },
        ),
    ]
