# Generated by Django 4.2.21 on 2025-05-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballers', '0005_stories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stories/images/'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='stories/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='stories/videos/'),
        ),
    ]
