# Generated by Django 4.2.21 on 2025-05-20 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footballers', '0006_alter_stories_image_alter_stories_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='image',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='video',
        ),
        migrations.CreateModel(
            name='StoryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='stories/media/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of media item in the story')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='footballers.stories')),
            ],
            options={
                'verbose_name': 'Медиа сториса',
                'verbose_name_plural': 'Медиа сторисов',
                'ordering': ['order'],
            },
        ),
    ]
