# Generated by Django 4.2.21 on 2025-05-17 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.FileField(upload_to='club_image', verbose_name='Картинка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клубы',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, default='0:0', max_length=250, null=True, verbose_name='Результат')),
                ('date_at', models.DateField(blank=True, null=True, verbose_name='Дата матча')),
                ('time_at', models.TimeField(blank=True, null=True, verbose_name='Время матча')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('location', models.CharField(max_length=255, verbose_name='Локация')),
                ('championship', models.CharField(max_length=255, verbose_name='Чемпионат')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('first_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_club_match', to='matches.club', verbose_name='Первый клуб')),
                ('second_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_club_match', to='matches.club', verbose_name='Второй клуб')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ('-id',),
            },
        ),
    ]
